services:
  app:
    build:
      context: .
      dockerfile: /docker/php/Dockerfile
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: idkdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: y@suk321
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: